"""empty message

Revision ID: 592c49e61fc0
Revises: a90dc5c3cf20
Create Date: 2023-01-03 23:44:38.062550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592c49e61fc0'
down_revision = 'a90dc5c3cf20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_num', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('brand_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('seller_id', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('seller_id')
        batch_op.drop_column('brand_id')
        batch_op.drop_column('sale_num')

    # ### end Alembic commands ###
